version: '2'
services:

  weather_db:
    image: weather_prediction_db:1.0
    container_name: weather_prediction_db
    hostname: weather_prediction_db
    restart: always
    networks:
      - prediction_network      
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: admin
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes: 
      - /tmp/workflow/data/:/var/lib/mysql

  prediction_flask:
    build: ./flask-api
    image: prediction_service_flask:1.0
    container_name: prediction_service_flask
    hostname: prediction_service_flask
    restart: always
    networks:
      - prediction_network
    depends_on:
      - weather_db
    expose:
      - 5000
    ports:
      - 5000:5000
    command: ['python', 'api.py']
    
  prediction_spring:
      build: ./spring-api
      image: prediction_service_spring:1.0
      container_name: prediction_service_spring
      hostname: prediction_service_spring
      restart: always
      networks:
        - prediction_network
      expose:
        - 8081
      ports:
        - 8081:8081
networks:
    prediction_network: